name: minesweeper
description: An implementation of the classic minesweeper game in Flutter!

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  rxdart: any
  shared_preferences: any


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
